# Generated by Django 5.0.4 on 2024-05-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('wanted', 'Wanted'), ('waiting', 'Waiting'), ('reading', 'Reading'), ('read', 'Read')], default='waiting', max_length=20),
        ),
    ]
